name: C/C++ CI

on:
  push:
    branches: [ newtype ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: apt-get
      run: sudo apt-get cmake libboost-iostreams-dev libboost-test-dev
    - name: cmake
      run: |
        mkdir build
        cd build
        cmake .. -DCMAKE_BUILD_TYPE=Debug -DBUILD_TESTING=on
    - name: test
      run: make test
