name: C/C++ CI

on:
  push:
    branches: [ master, api_change ]
  pull_request:
    branches: [ master, api_change ]

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
    - name: apt-get
      run: sudo apt-get install cmake libboost-iostreams-dev libboost-system-dev libboost-test-dev libjsoncpp-dev libfftw3-dev libclfft-dev
    - name: cmake
      run: |
        mkdir build
        cd build
        cmake .. -DCMAKE_BUILD_TYPE=Debug -DBUILD_TESTING=on -DISIS_USE_FFTW=on
    - name: make
      run: |
        cd build
        make
    - name: test
      run: |
        cd build
        make test
